name: Lint & Security

on:
  pull_request:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
      - "bandit.yaml"
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -e ".[dev]"
      - name: Ruff (strict, no-fix)
        run: ruff check .
      - name: Black check
        run: black --check --line-length=120 .

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install bandit[toml]
      - name: Bandit
        run: bandit -r osiris -c bandit.yaml -q
